In [1]:
import NuRadioReco.detector.detector
import astropy.time
import skspatial.objects as skspob
import skspatial.plotting as sksplt
import math
import h5py
import re
import numpy as np

In [2]:
H5pyFile = h5py.File("SIM000001.hdf5", "r")

In [4]:
H5pyFile.keys()

<KeysViewHDF5 ['atmosphere', 'inputs', 'observers']>

In [25]:
f["inputs"].attrs.keys()

<KeysViewHDF5 ['AlternativeSmooth', 'Azi_sh', 'D_ESmooth', 'ENERGY_SH2', 'F_lim', 'Fit_StI', 'GROUNDLEVEL', 'IntegrateCurrent', 'Intensity_Weight', 'Intensity_weight', 'J0Q', 'J0T', 'MOLIERERADIUS', 'ObsDist_dim', 'OutFileLabel', 'RnrmA', 'RnrmB', 'SAMPLINGTIME', 'StParRange', 'X_02', 'X_MAX2', 'X_max', 'Zen_sh', 'azi_B', 'energy_sh', 'lamx', 'lamx2', 'nu_max', 'nu_min', 'u0', 'x_0', 'zen_B']>

In [37]:
ki = H5pyFile["observers/pos_010_045"]
for item in ki.attrs:
    print(ki.attrs[item])

[b't_us' b'Re_Ex' b'Im_Ex' b'Re_Ey' b'Im_Ey']
[7.07106781 7.07106781]
[b'nano s' b'microV/m' b'microV/m' b'microV/m' b'microV/m']


In [36]:
ki.attrs["columns"]

array([b't_us', b'Re_Ex', b'Im_Ex', b'Re_Ey', b'Im_Ey'], dtype='|S5')

In [95]:
CoordinatesDetectors = np.zeros([632,2])
NameDetectors = list([] for _ in range(632))
amount_iters = 0
for item in H5pyFile["observers"]:
    NameDetectors[amount_iters] = item
    split = re.split('_',item)
    CoordinatesDetectors[amount_iters,0] = split[1]
    CoordinatesDetectors[amount_iters,1] = split[2]
    amount_iters = amount_iters+1
distances = np.unique(observers[:,0],return_counts = True)
NameDetectors = tuple(NameDetectors)

In [29]:
kl = H5pyFile["observers"]
for item in kl:
    test = kl[item]
    print(test[1542])

[-2.4964e-02 -4.1510e-07 -5.1830e-05 -7.0900e-08 -2.5290e-06]
[-2.4964e-02 -3.4410e-07 -4.9300e-05 -1.0030e-07 -3.5770e-06]
[-2.4964e-02 -2.7320e-07 -4.6770e-05 -7.0900e-08 -2.5290e-06]
[-2.4964e-02 -2.4390e-07 -4.5730e-05 -1.2280e-23 -4.3810e-22]
[-2.4964e-02 -2.7320e-07 -4.6770e-05  7.0900e-08  2.5290e-06]
[-2.4964e-02 -3.4410e-07 -4.9300e-05  1.0030e-07  3.5770e-06]
[-2.4964e-02 -4.1510e-07 -5.1830e-05  7.0900e-08  2.5290e-06]
[-2.4964e-02 -4.4440e-07 -5.2880e-05  2.4560e-23  8.7620e-22]
[-2.4964e-02 -8.2380e-07 -5.8700e-05 -5.1180e-07 -8.4110e-06]
[-2.4964e-02 -3.1200e-07 -5.0290e-05 -7.2370e-07 -1.1900e-05]
[-2.4964e-02  1.9980e-07 -4.1880e-05 -5.1180e-07 -8.4110e-06]
[-2.4964e-02  4.1170e-07 -3.8390e-05 -8.8630e-23 -1.4570e-21]
[-2.4964e-02  1.9980e-07 -4.1880e-05  5.1180e-07  8.4110e-06]
[-2.4964e-02 -3.1200e-07 -5.0290e-05  7.2370e-07  1.1900e-05]
[-2.4964e-02 -8.2380e-07 -5.8700e-05  5.1180e-07  8.4110e-06]
[-2.4964e-02 -1.0360e-06 -6.2180e-05  1.7730e-22  2.9130e-21]
[-2.4964

In [79]:
kl = H5pyFile["observers"]

In [83]:
kl["pos_010_045"]

<HDF5 dataset "pos_010_045": shape (5468, 5), type "<f8">